DROP DATABASE IF EXISTS personnel;
CREATE DATABASE personnel;
USE personnel;

CREATE TABLE DEPT(
	DEPTNO INT(2) NOT NULL,
	DNAME VARCHAR(15),
	PRIMARY KEY(DEPTNO));
	
CREATE TABLE JOB(
	JOBNO INT(3) NOT NULL,
	JOB VARCHAR(15),
	SAL FLOAT(7,2),
	PRIMARY KEY(JOBNO));

CREATE TABLE EMP(
	EMPNO INT(4) NOT NULL,
	ENAME VARCHAR(10),
	JOBCODE INT(3),
	DEPTNO INT(2),
	PRIMARY KEY(EMPNO),
	FOREIGN KEY(JOBCODE) REFERENCES JOB(JOBNO),
	FOREIGN KEY(DEPTNO) REFERENCES DEPT(DEPTNO));
	
INSERT INTO DEPT VALUES
	(10, 'ACCOUNTING'),
	(20, 'SALES'),
	(30, 'PERSONNEL');
	

INSERT INTO JOB VALUES
	(100, 'DBA', 2500),
	(200, 'ANALYST', 2000);

INSERT INTO EMP VALUES
	(1000, 'SMITH', 100, 10),
	(2000, 'TOM', 200, 10),
	(300, 'JIM', 100, 20),
	(400, 'BOB', 200, 20);
