/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_H_RPCGEN
#define _RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct nX {
	int n;
	struct {
		u_int X_len;
		int *X_val;
	} X;
};
typedef struct nX nX;

struct nXY {
	int n;
	struct {
		u_int X_len;
		int *X_val;
	} X;
	struct {
		u_int Y_len;
		int *Y_val;
	} Y;
};
typedef struct nXY nXY;

struct nXYr {
	int n;
	struct {
		u_int X_len;
		int *X_val;
	} X;
	struct {
		u_int Y_len;
		int *Y_val;
	} Y;
	float r;
};
typedef struct nXYr nXYr;

struct float_array {
	struct {
		u_int arr_len;
		float *arr_val;
	} arr;
};
typedef struct float_array float_array;

#define xMeasure_PROG 0x20000000
#define xMeasure_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define xMeasure 1
extern  float * xmeasure_1(nX *, CLIENT *);
extern  float * xmeasure_1_svc(nX *, struct svc_req *);
extern int xmeasure_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define xMeasure 1
extern  float * xmeasure_1();
extern  float * xmeasure_1_svc();
extern int xmeasure_prog_1_freeresult ();
#endif /* K&R C */

#define xyInnerProd_PROG 0x20001000
#define xyInnerProd_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define xyInnerProd 1
extern  int * xyinnerprod_1(nXY *, CLIENT *);
extern  int * xyinnerprod_1_svc(nXY *, struct svc_req *);
extern int xyinnerprod_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define xyInnerProd 1
extern  int * xyinnerprod_1();
extern  int * xyinnerprod_1_svc();
extern int xyinnerprod_prog_1_freeresult ();
#endif /* K&R C */

#define xyAvg_PROG 0x20002000
#define xyAvg_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define xyAvg 1
extern  struct float_array * xyavg_1(nXY *, CLIENT *);
extern  struct float_array * xyavg_1_svc(nXY *, struct svc_req *);
extern int xyavg_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define xyAvg 1
extern  struct float_array * xyavg_1();
extern  struct float_array * xyavg_1_svc();
extern int xyavg_prog_1_freeresult ();
#endif /* K&R C */

#define xyRProd_PROG 0x20003000
#define xyRProd_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define xyRProd 1
extern  struct float_array * xyrprod_1(nXYr *, CLIENT *);
extern  struct float_array * xyrprod_1_svc(nXYr *, struct svc_req *);
extern int xyrprod_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define xyRProd 1
extern  struct float_array * xyrprod_1();
extern  struct float_array * xyrprod_1_svc();
extern int xyrprod_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nX (XDR *, nX*);
extern  bool_t xdr_nXY (XDR *, nXY*);
extern  bool_t xdr_nXYr (XDR *, nXYr*);
extern  bool_t xdr_float_array (XDR *, float_array*);

#else /* K&R C */
extern bool_t xdr_nX ();
extern bool_t xdr_nXY ();
extern bool_t xdr_nXYr ();
extern bool_t xdr_float_array ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_H_RPCGEN */
